dsc/Cargo.toml, dsc/src/args.rs, dsc_lib/Cargo.toml
Update version so that `dsc -V` shows the right version for next release
=> update version to next release

CHANGELOG.md, docs/reference/cli/resource/set.md, docs/reference/schemas/resource/manifest/get.md, docs/reference/schemas/resource/manifest/root.md, docs/reference/schemas/resource/manifest/set.md, docs/reference/schemas/resource/manifest/test.md
This change updates the reference documentation and the changelog to reflect the changes that were included in the `alpha.3` release:
- #197
- #198
- #199
=> (DOCS) Update docs and changelog for `alpha.3`

.gitignore, package-lock.json, package.json
Add generated code from tree-sitter to .gitignore
Include package*.json files so everyone is using same dependency versions
=> update tree-sitter files

CHANGELOG.md
This change adds changelog entries for #240 to the CHANGELOG.
N/A
=> (DOCS) Add resource discovery updates to CHANGELOG

.vsts-ci/release.yml, build.ps1, package-lock.json, tree-sitter-dscexpression/build.ps1, tree-sitter-dscexpression/package-lock.json
Enable signed and SBOM release packages
=> Release pipeline

.vsts-ci/release.yml
=> fix signing scripts

CHANGELOG.md
Updates the links and headings for `alpha.4`.
This sets up the changelog for entries that will make it into `alpha.5` and readies the documentation to be pulled across to the Learn platform.
=> (RELEASE) Update Changelog for `alpha.4`

CHANGELOG.md, docs/reference/cli/dsc.md
This change documents the updated options due to tracing formatting in the root command.
N/A
=> (DOCS) Changes to top-level options

build.ps1
- remove duplicate tools/dsctest from build list
- tools/dsctest is duplicated on line 118 and line 124
=> remove duplicate project from build list

CHANGELOG.md, docs/reference/cli/config/export.md, docs/reference/cli/config/get.md, docs/reference/cli/config/set.md, docs/reference/cli/config/test.md, docs/reference/cli/dsc.md, docs/reference/cli/resource/export.md, docs/reference/cli/resource/get.md, docs/reference/cli/resource/list.md, docs/reference/cli/resource/schema.md, docs/reference/cli/resource/set.md, docs/reference/cli/resource/test.md, docs/reference/cli/schema/command.md
This change updates the CLI reference and changelog to reflect the refactored global options.
For reference, see:
- #305
- #303
=> (DOCS) Options refactor

dsc/Cargo.toml, dsc_lib/Cargo.toml
Update the version to next release
=> update to next version

dsc/Cargo.toml, dsc/src/util.rs
- fix #337
- use tracing indicatif to sync tracing and progress bar rendering
=> use tracing indicatif to sync tracing and progress bar rendering

dsc_lib/src/functions/div.rs, dsc_lib/src/functions/mod.rs
- implement https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-numeric#div
- part of #57
=> add div function

dsc_lib/src/functions/add.rs, dsc_lib/src/functions/mod.rs
- implement https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-numeric#add
- part of #57
=> implement add function

dsc/Cargo.toml, dsc_lib/Cargo.toml, dsc_lib/src/configure/context.rs
Update next version to preview.7
- we are basically feature complete with known issues that need to be addressed, but the fundamental design is pretty much set
- we need to skip a 6 release as I've published a test msix to the store and the store requires the versions to be unique
=> update version to preview.7

dsc_lib/src/functions/max.rs, dsc_lib/src/functions/mod.rs
- implement https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-numeric#max
- part of #57
=> add max function

.pipelines/DSC-Official.yml, build.ps1
- Fixed working paths for jobs
- Moved tar.gz and zip creation to build.ps1
- Refactored package creation in build.ps1
- Proper upload and download in release pipeline
- Redid packaging and signing to accommodate subdirs
- Only specific files get included in each package: Windows, Linux, macOS so test artifacts are no longer included
=> Release pipeline updates

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SECURITY.md
Updates the readme, code of conduct, security policy and contributing document per OSPO request.
OSPO has requested us to update these documents like so.
=> Update Code of Conduct and Security Policy

dsc/Cargo.toml, dsc/src/main.rs, pal/src/windows.rs
- update version to next release
- update some crates to newer versions
- small fix due to change in crate version
=> update version string and crate versions

powershell-adapter/psDscAdapter/psDscAdapter.psm1, powershell-adapter/psDscAdapter/win_psDscAdapter.psm1
Recent checkin had a bad 3-way merge that broke WinPSAdapter.
This PR fixes that.
=> WinPSAdapter fix

dsc/Cargo.toml
Update version for next release
=> Update version to preview.10

dsc/Cargo.lock, dsc/Cargo.toml, dsc_lib/Cargo.lock, dsc_lib/Cargo.toml, dsc_lib/src/parser/mod.rs, tools/test_group_resource/Cargo.lock, tree-sitter-dscexpression/Cargo.lock, tree-sitter-dscexpression/Cargo.toml
Looks like the tree-sitter crate made a breaking change so this addresses that
=> Fix use of tree-sitter binding due to change in crate

dsc/Cargo.lock, dsc/Cargo.toml
`main` branch is now 3.1-preview.1
=> update version to 3.1-preview.1

.github/workflows/rust.yml, dsc/Cargo.lock, dsc/Cargo.toml
Update version to 3.0.0 for GA
Enable Actions on this branch
=> Version 3.0.0

powershell-adapter/Tests/powershellgroup.config.tests.ps1, powershell-adapter/psDscAdapter/powershell.resource.ps1
Backport of https://github.com/PowerShell/DSC/pull/647 for 3.0
=> Backport: PSAdapter cache limit fix

dsc/Cargo.lock, dsc/src/args.rs, dsc/src/main.rs, dsc/src/subcommand.rs, dsc/tests/dsc_args.tests.ps1, dsc/tests/dsc_config_get.tests.ps1, dsc/tests/dsc_resource_list.tests.ps1, dsc_lib/Cargo.lock, dsc_lib/Cargo.toml, dsc_lib/locales/en-us.toml, dsc_lib/src/configure/mod.rs, dsc_lib/src/discovery/command_discovery.rs, dsc_lib/src/discovery/discovery_trait.rs, dsc_lib/src/discovery/mod.rs, dsc_lib/src/lib.rs, dsc_lib/src/progress.rs, dsc_lib/src/util.rs, dscecho/Cargo.lock, osinfo/Cargo.lock, process/Cargo.lock, runcommandonset/Cargo.lock, security_context_lib/Cargo.lock, tools/dsctest/Cargo.lock, tools/test_group_resource/Cargo.lock, tree-sitter-dscexpression/Cargo.lock, y2j/Cargo.lock
- Backport of https://github.com/PowerShell/DSC/pull/644 for 3.0
- Update lockfiles
=> Backport: progress json updates

dsc/Cargo.lock, dsc/Cargo.toml
Update version to `3.1-preview.2`
=> Update version to 3.1-preview.2

dsc_lib/src/dscresources/command_resource.rs, powershell-adapter/Tests/win_powershellgroup.tests.ps1, powershell-adapter/psDscAdapter/powershell.resource.ps1, powershell-adapter/psDscAdapter/psDscAdapter.psm1, powershell-adapter/psDscAdapter/win_psDscAdapter.psm1
Fix some issues in psadapter specifically the case where you have multiple versions of the same dsc resource module and the adapter fails to create the module specification.
This will be for a 3.0.1 release
=> Backport 3.0: Add better tracing and fix propagation of inDesiredState

dsc/Cargo.lock, dsc/Cargo.toml
=> Update version to 3.0.1

.config/tsaoptions.json
=> Update contact information

powershell-adapter/powershell.dsc.resource.json, powershell-adapter/windowspowershell.dsc.resource.json
Backport of https://github.com/PowerShell/DSC/pull/715 for 3.0
=> Backport: Set bypass executionpolicy when calling PowerShell

.config/tsaoptions.json
Backport of https://github.com/PowerShell/DSC/pull/735
=> Backport: Update contact information

dsc/Cargo.lock, dsc/Cargo.toml
Update version for 3.0.2 release
=> Update version to 3.0.2

dsc/Cargo.lock, dsc/Cargo.toml, dsc_lib/Cargo.lock, dsc_lib/Cargo.toml, registry/Cargo.lock, registry/Cargo.toml, tools/test_group_resource/Cargo.lock
Update version to 3.1-preview.3
Updated versions of some crates
=> update version to 3.1-preview.3

dsc/assertion.dsc.resource.json, dsc/examples/assertion.dsc.yaml, dsc/locales/en-us.toml, dsc/src/args.rs, dsc/src/main.rs, dsc/src/subcommand.rs, dsc/src/util.rs, dsc/tests/dsc_assertion.tests.ps1, dsc/tests/dsc_config_test.tests.ps1
Backport https://github.com/PowerShell/DSC/pull/736
=> Backport: assertion resource fix

dsc/src/resource_command.rs, dsc/src/subcommand.rs, dsc/src/tablewriter.rs, dsc/src/util.rs, dsc_lib/src/configure/mod.rs, dsc_lib/src/discovery/command_discovery.rs, dsc_lib/src/dscresources/command_resource.rs, dsc_lib/src/schemas/mod.rs, dsc_lib/src/util.rs, registry/src/main.rs, registry/src/registry_helper.rs
=> Fix new clippy rule issues

.pipelines/DSC-Official.yml, build.ps1
For official build use msrustup, for all other builds use `msrustup` if found, otherwise fallback to `rustup`
=> Change build to prefer msrustup

dsc/Cargo.lock, dsc/Cargo.toml
Update version to 3.1.0-preview.4
=> Update version to 3.1.0-preview.4

build.ps1
=> Add shebang to build.ps1 so it's runnable

wmi-adapter/wmi.dsc.resource.json
Set executionpolicy to bypass for WMI DSC resource. Relates to #715.
=> Add executionpolicy WMI

dsc/Cargo.lock, dsc/Cargo.toml, dsc_lib/Cargo.lock, osinfo/Cargo.lock, osinfo/Cargo.toml, runcommandonset/Cargo.toml, security_context_lib/Cargo.lock, security_context_lib/Cargo.toml, tools/test_group_resource/Cargo.lock, tree-sitter-dscexpression/Cargo.lock, tree-sitter-dscexpression/Cargo.toml, y2j/Cargo.toml
Update version to 3.1.0-preview.6 and crate versions
=> Update version to 3.1.0-preview.6 and crate versions

build.ps1, dsc_lib/locales/en-us.toml, dsc_lib/src/discovery/command_discovery.rs, dsc_lib/src/extensions/dscextension.rs, extensions/appx/appx-discover.ps1, extensions/appx/appx.dsc.extension.json, extensions/appx/appx.tests.ps1, extensions/appx/copy_files.txt
Experimental discovery extension to find resources that are packaged as part of an Appx package
Also updated discovery to remove duplicates (matching resource type name and version)
=> Experimental Appx resource discovery extension

.github/workflows/rust.yml, dsc/Cargo.lock, dsc/Cargo.toml
Update 3.1 release branch version to 3.1-rc
=> Update version to 3.1-rc.1

.github/workflows/rust.yml, dsc/Cargo.lock, dsc/Cargo.toml
`main` branch is now `3.2`, update version to 3.2-preview.1 and enable CI for release branches
=> Update version to 3.2-preview.1 and enable CI in release branches

registry/src/main.rs, registry_lib/src/lib.rs
- add `new()` RegistryHelper constructor that takes params in directly instead of from json
- refactor that coincides with sshdconfig default shell changes
=> refactor registry lib

dscecho/echo.dsc.resource.json
Echo resource was missing a description
Fix https://github.com/PowerShell/DSC/issues/914
=> Add description to Echo resource

.pipelines/DSC-Official.yml
Basically needed signing step as separate job and using correct signing profile
Fix https://github.com/PowerShell/DSC/issues/921
=> Fix msixbundle store signing

dsc/Cargo.lock, dsc/Cargo.toml, dsc/src/resource_command.rs
Backport of #920 to 3.1
Also update version to 3.1.1
=> Backport: Fix default output to YAML when used interactively

.pipelines/DSC-Official.yml
Enable release pipeline to publish symbols
=> Publish symbols

docs/reference/schemas/config/functions/reference.md
Found by @ThomasNieto. This fixes the example, as the actualState did not exist.
=> Update reference example

docs/reference/schemas/overview.md
This PR fixes a small typo in the schema article.
=> Small typo in schema article

es-metadata.yml
=> Add metadata for inventory

rfc/RFC0000-rfc-process.md
=> Fix typo in RFC0000

docs/reference/schemas/config/functions/range.md, dsc/tests/dsc_functions.tests.ps1, dsc_lib/locales/en-us.toml, dsc_lib/src/functions/mod.rs, dsc_lib/src/functions/range.rs
This pull request adds the `range()` function, along with its reference documentation.
Partially addresses #57.
=> Add `range()` function

.pipelines/DSC-Official.yml
Use deploy box to perform the release. This includes releasing packages to a universal feed and publishing it to GitHub as a draft.
=> Deploybox release
